image: node:alpine
pages:
  stage: deploy
  script:
    - npm install
    - npm run build
    - rm -rf public
    - mv build public
    - mv dependencygraph.html public/
  artifacts:
    paths:
      - public
  only:
    - master
test: 
    stage: test
     script:
    - npm install
    - npm run build
    - rm -rf test
    - mv build test
    - mv dependencygraph.html test/
    artifacts:
        paths:
            - test
    except:
        -master
    
variables:
  PUBLIC_URL: "/assessment---kwitter-frontend"